### ISSUE TITLE
Whisper parameters

### ISSUE THREAD

**Issue by skanda1005** [huggingface/community-events#107]
Can I use whisper parameters like beam_size and temperature while running my finetuned hf model?

**Comment by Vaibhavs10** [comment]
Hi @skanda1005 - Yes! You should be able to use all the parameters in `model.generate` with any Whisper checkpoint: https://huggingface.co/docs/transformers/main_classes/text_generation#transformers.GenerationConfig.num_beams

Do let me know if you face any issues with it.
