### ISSUE TITLE
Lambda platform doesn't support Tensorflow-Gpu

### ISSUE THREAD

**Issue by kadirnar** [huggingface/community-events#118]
@merveenoyan ,

NVIDIA-SMI 515.65.01    
Driver Version: 515.65.01    
CUDA Version: 11.7
TensorFlow: 2.11.0

![image](https://user-images.githubusercontent.com/36204372/223962033-811ba307-feb0-4263-bff8-4501e609548f.png)
The pytorch library supports it, but tensorflow doesn't.

TF:
```
tf.config.list_logical_devices("GPU")
```
Output:
```
[]
```
Torch:
```
import torch
torch.cuda.is_available()
```
Output:
```
True
```

**Comment by merveenoyan** [comment]
Lambda does support tensorflow with GPU, I will put CUDA installation command to the guide.
