### ISSUE TITLE
Whisper finetune

### ISSUE THREAD

**Issue by Macsim2** [huggingface/community-events#184]
Hi I'm trying to train whisper fine-tune with multi-gpu
and I don't know what `RANK` to set
I just set `WORLD_SIZE` is numer of gpu and `MASTER_ADDR` is localhost, `MASTER_PORT` is idle port
When `WORLD_SIZE` is more than 2 and `RANK` is set 0, training is hanging 
Probably it hanged in setting torch.distributed.TCPStore() part..

anyone who solved this problem?
let me know hint please

**Comment by sanchit-gandhi** [comment]
Hey @Macsim2! You should just be able to launch multi-GPU training using `torchrun`, as shown here: https://github.com/huggingface/transformers/tree/main/examples/pytorch/speech-recognition#multi-gpu-whisper-training

Let me know if you encounter any difficulties!

**Comment by sneha117** [comment]
> Hey @Macsim2! You should just be able to launch multi-GPU training using `torchrun`, as shown here: https://github.com/huggingface/transformers/tree/main/examples/pytorch/speech-recognition#multi-gpu-whisper-training
> 
> Let me know if you encounter any difficulties!

is it possible to use this and train on a custom dataset.

**Comment by Macsim2** [comment]
@sneha117 Thank you
