### ISSUE TITLE
Issue uploading the dataset

### ISSUE THREAD

**Issue by vendrick17** [huggingface/community-events#25]
Hi, I tried to upload my dataset to the Hub but I am getting this error message 

`HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/api/repos/create - You don't have the rights to create a dataset under this namespace`

I tried changing the permissions of the token (write and read) but it didn't work. Any help will be appreciated.

**Comment by osanseviero** [comment]
Hey there! Did you use a write token from your own account?
